### ISSUE TITLE
FYI: GitVersion is deprecated. Use GitTools bundle extension instead

### ISSUE THREAD

**Issue by phbits** [dsccommunity/dsccommunity.org#155]
While working through the DSC Community guidelines for [contributing](https://dsccommunity.org/guidelines/contributing/) I found [GitVersion](https://marketplace.visualstudio.com/items?itemName=gittools.gitversion) showed:

> [DEPRECATED] This extension is deprecated. Use GitTools bundle extension instead

Installing GitTools doesn't work so there seems to be no backward compatibility. Had to install GitVersion to continue.

**Comment by PlagueHO** [comment]
@gaelcolas - does indeed look like the GitVerson extension is deprecated. @phbits - I don't think GitTools is enabled in the DSCCommunity Azure DevOps org - which is probably why it doesn't work. I could be wrong though....

**Comment by PlagueHO** [comment]
Incidentally, I converted one of my pipelines over to the new extension by replacing the task with these two:
```yaml
          - task: gittools.gittools.setup-gitversion-task.gitversion/setup@0
            displayName: 'Setup GitVersion'
            inputs:
              versionSpec: 5.x

          - task: gittools.gittools.execute-gitversion-task.gitversion/execute@0
            displayName: 'Evaluate Next Version'
            inputs:
              useConfigFile: true
              configFilePath: 'GitVersion.yml'
```
